version: 0.2

env:
  variables:
    AWS_REGION: ap-south-2
    ECR_REPO: myapp-prod
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_URI/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "Build completed successfully"
      - echo "IMAGE_URI=$ECR_URI/$ECR_REPO_NAME:$IMAGE_TAG" > imageDetail.txt


artifacts:
  files:
    - imagedefinitions.json
